/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        brand: 'hsl(85, 33%, 50%)',
        forest: 'hsl(132, 38%, 12%)',
        // ── Semantic tokens (map to CSS variables) ──────────────
        bg: {
          primary:   'var(--bg-primary)',
          secondary: 'var(--bg-secondary)',
          tertiary:  'var(--bg-tertiary)',
        },
        surface: {
          DEFAULT:  'var(--surface)',
          elevated: 'var(--surface-elevated)',
          hover:    'var(--surface-hover)',
          active:   'var(--surface-active)',
        },
        text: {
          primary:   'var(--text-primary)',
          secondary: 'var(--text-secondary)',
          muted:     'var(--text-muted)',
          inverse:   'var(--text-inverse)',
        },
        border: {
          DEFAULT: 'var(--border)',
          subtle:  'var(--border-subtle)',
          strong:  'var(--border-strong)',
          focus:   'var(--border-focus)',
        },
        sidebar: {
          bg:     'var(--sidebar-bg)',
          border: 'var(--sidebar-border)',
          text:   'var(--sidebar-text)',
          active: 'var(--sidebar-text-active)',
          item:   'var(--sidebar-item-active)',
          hover:  'var(--sidebar-item-hover)',
        },
        action: {
          primary: 'var(--action-primary)',
          hover:   'var(--action-primary-hover)',
          text:    'var(--action-primary-text)',
        },
        status: {
          success:        'var(--success)',
          'success-bg':   'var(--success-bg)',
          'success-text': 'var(--success-text)',
          warning:        'var(--warning)',
          'warning-bg':   'var(--warning-bg)',
          'warning-text': 'var(--warning-text)',
          danger:         'var(--danger)',
          'danger-bg':    'var(--danger-bg)',
          'danger-text':  'var(--danger-text)',
          info:           'var(--info)',
          'info-bg':      'var(--info-bg)',
          'info-text':    'var(--info-text)',
        },

        // ── Legacy palette colors (kept for compatibility) ──────
        ink:      'var(--text-primary)',
        ink2:     'var(--text-secondary)',
        paper:    'var(--surface)',
        paperDim: 'var(--bg-secondary)',
        ledger:   '#132A13',
        ledgerDark: 'var(--bg-primary)',
        ledgerLight: 'var(--border-subtle)',
        rust:     'var(--warning)',
        rustLight:'var(--warning-bg)',
        line:     'var(--border)',
        muted:    'var(--text-muted)',
        success: { DEFAULT: '#10B981', dark: '#047857', light: '#E5F8F1' },
        warning: { DEFAULT: '#F59E0B', dark: '#B45309', light: '#FEF3E2' },
        danger: { DEFAULT: '#EF4444', dark: '#B91C1C', light: '#FDEAEA' },
        info: { DEFAULT: '#3B82F6', dark: '#1D4ED8', light: '#EAF1FE' },
      },
      fontFamily: {
        display: ['"Inter"', 'sans-serif'],
        body: ['"Inter"', 'sans-serif'],
        mono: ['"IBM Plex Mono"', 'monospace'],
      },
      boxShadow: {
        card: '0 1px 2px rgba(18,24,27,0.04), 0 1px 8px rgba(18,24,27,0.03)',
        raised: '0 4px 14px rgba(18,24,27,0.08), 0 1px 3px rgba(18,24,27,0.06)',
        popover: '0 12px 32px rgba(18,24,27,0.14), 0 2px 6px rgba(18,24,27,0.08)',
      },
      borderRadius: { xl2: '1rem' },
      keyframes: {
        fadeIn: { from: { opacity: 0 }, to: { opacity: 1 } },
        slideUp: { from: { opacity: 0, transform: 'translateY(6px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        slideDown: { from: { opacity: 0, transform: 'translateY(-6px)' }, to: { opacity: 1, transform: 'translateY(0)' } },
        toastIn: { from: { opacity: 0, transform: 'translateX(16px) scale(0.97)' }, to: { opacity: 1, transform: 'translateX(0) scale(1)' } },
        scaleIn: { from: { opacity: 0, transform: 'scale(0.96)' }, to: { opacity: 1, transform: 'scale(1)' } },
        shimmer: { from: { backgroundPosition: '-400px 0' }, to: { backgroundPosition: '400px 0' } },
      },
      animation: {
        fadeIn: 'fadeIn .18s ease-out',
        slideUp: 'slideUp .22s cubic-bezier(0.16,1,0.3,1)',
        slideDown: 'slideDown .18s ease-out',
        toastIn: 'toastIn .25s cubic-bezier(0.16,1,0.3,1)',
        scaleIn: 'scaleIn .16s cubic-bezier(0.16,1,0.3,1)',
        shimmer: 'shimmer 1.4s infinite linear',
      },
    },
  },
  plugins: [],
};
