export const AUXILIARY_ROUTES = [
  { path: 'payroll/structure', resourceType: 'payroll-structure', title: 'Salary' },
  { path: 'settings/credentials', resourceType: 'settings-credentials', title: 'Send Employee Login Credentials' },
  { path: 'organization/import', resourceType: 'organization-import', title: 'Import Reporting Managers & EmailId' },
  { path: 'tax-calculator/pending', resourceType: 'tax-calculator-pending', title: 'Pending Employee TDS Declarations' },
  { path: 'tax-calculator/master', resourceType: 'tax-calculator-master', title: 'Employee TDS Declaration Master' },
  { path: 'tax-calculator/declarations', resourceType: 'tax-calculator-declarations', title: 'Employee TDS Declaration List' },
  { path: 'attendance/daily', resourceType: 'attendance-daily', title: 'Apply Attendance' },
  { path: 'attendance/manual', resourceType: 'attendance-manual', title: 'Update Attendance' },
  { path: 'attendance/custom', resourceType: 'attendance-custom', title: 'Emp Custom Daily Attendance' },
  { path: 'attendance/regularization', resourceType: 'attendance-regularization', title: 'Attendance Regularisation' },
  { path: 'attendance/overtime', resourceType: 'attendance-overtime', title: 'Overtime' },
  { path: 'attendance/geofence', resourceType: 'attendance-geofence', title: 'Geo Attendance' },
  { path: 'attendance/daily-report', resourceType: 'attendance-daily-report', title: 'Daily Attendance Report' },
  { path: 'attendance/summary', resourceType: 'attendance-summary', title: 'Monthly Attendance Report' },
  { path: 'leave/requests', resourceType: 'leave-requests', title: 'Leave Requests List' },
  { path: 'leave/balances', resourceType: 'leave-balances', title: 'Leave Balance' },
  { path: 'leave/compoff', resourceType: 'leave-compoff', title: 'Comp Off' },
  { path: 'payroll/attendance-process', resourceType: 'payroll-attendance-process', title: 'Attendance Process' },
  { path: 'payroll/additional-payout', resourceType: 'payroll-additional-payout', title: 'Additional Salary Payout' },
  { path: 'payroll/monthly', resourceType: 'payroll-monthly', title: 'Run Payroll' },
  { path: 'payroll/processed', resourceType: 'payroll-processed', title: 'View Processed Salary' },
  { path: 'payroll/send-payslips', resourceType: 'payroll-send-payslips', title: 'Send Payslips' },
  { path: 'payroll/arrears', resourceType: 'payroll-arrears', title: 'Arrears' },
  { path: 'payroll/history', resourceType: 'payroll-history', title: 'Salary History' },
  { path: 'payroll/bonus', resourceType: 'payroll-bonus', title: 'Bonus' },
  { path: 'expenses/advance', resourceType: 'expenses-advance', title: 'Advance Claim' },
  { path: 'performance/kpa', resourceType: 'performance-kpa', title: 'KPA' },
  { path: 'performance/kpi-list', resourceType: 'performance-kpi-list', title: 'KRA/KPI List' },
  { path: 'performance/assign-kpi', resourceType: 'performance-assign-kpi', title: 'Assign KPI' },
  { path: 'performance/kra', resourceType: 'performance-kra', title: 'KRA' },
  { path: 'performance/kpi', resourceType: 'performance-kpi', title: 'KPI' },
  { path: 'performance/annual-target', resourceType: 'performance-annual-target', title: 'Appraisal Year Target Setup' },
  { path: 'performance/periodic-target', resourceType: 'performance-periodic-target', title: 'Periodic Target Setup' },
  { path: 'performance/approve-targets', resourceType: 'performance-approve-targets', title: 'Approve Targets' },
  { path: 'performance/peer-eval', resourceType: 'performance-peer-eval', title: 'Peer Evaluation Setup' },
  { path: 'performance/external-eval', resourceType: 'performance-external-eval', title: 'External Evaluation Setup' },
  { path: 'performance/evaluation', resourceType: 'performance-evaluation', title: 'Employee Evaluation' },
  { path: 'performance/scorecard', resourceType: 'performance-scorecard', title: 'View Scorecard' },
  { path: 'performance/periodic-scorecard', resourceType: 'performance-periodic-scorecard', title: 'View Periodic Scorecard' },
  { path: 'performance/360-summary', resourceType: 'performance-360-summary', title: '360-Evaluation Summary' },
  { path: 'performance/forms', resourceType: 'performance-forms', title: 'More Forms' },
  { path: 'recruitment/panel', resourceType: 'recruitment-panel', title: 'Recruitment Panel Members' },
  { path: 'recruitment/job-description', resourceType: 'recruitment-job-description', title: 'Job Description' },
  { path: 'recruitment/job-ads', resourceType: 'recruitment-job-ads', title: 'Job Advertisement List' },
  { path: 'recruitment/consultants', resourceType: 'recruitment-consultants', title: 'Consultant Registration List' },
  { path: 'recruitment/requisitions-pending', resourceType: 'recruitment-requisitions-pending', title: 'Pending for Approval Requisition' },
  { path: 'recruitment/requisitions', resourceType: 'recruitment-requisitions', title: 'Requisitions' },
  { path: 'recruitment/requisitions-assigned', resourceType: 'recruitment-requisitions-assigned', title: 'Assigned Requisitions' },
  { path: 'recruitment/requisitions-assign', resourceType: 'recruitment-requisitions-assign', title: 'Assign Requisition' },
  { path: 'recruitment/resumes', resourceType: 'recruitment-resumes', title: 'Resume List' },
  { path: 'recruitment/resumes-pending', resourceType: 'recruitment-resumes-pending', title: 'Pending for Approval Resume List' },
  { path: 'recruitment/resumes-comments', resourceType: 'recruitment-resumes-comments', title: 'Comment On Resume List' },
  { path: 'recruitment/assign-screening', resourceType: 'recruitment-assign-screening', title: 'Assign Resume for screening' },
  { path: 'recruitment/interview-schedule', resourceType: 'recruitment-interview-schedule', title: 'Interview Schedule' },
  { path: 'recruitment/interviews', resourceType: 'recruitment-interviews', title: 'Interview Schedule List' },
  { path: 'recruitment/interview-feedback', resourceType: 'recruitment-interview-feedback', title: 'Interview FeedBack List' },
  { path: 'recruitment/interview-status', resourceType: 'recruitment-interview-status', title: 'Change Status-Interview' },
  { path: 'recruitment/selected-candidates', resourceType: 'recruitment-selected-candidates', title: 'Selected Candidates List' },
  { path: 'recruitment/approved-rejected', resourceType: 'recruitment-approved-rejected', title: 'Hiring Approved/Rejected candidates' },
  { path: 'recruitment/offer-letters', resourceType: 'recruitment-offer-letters', title: 'Offered candidates' },
  { path: 'recruitment/declined-candidates', resourceType: 'recruitment-declined-candidates', title: 'Offer Declined By Candidates List' },
  { path: 'recruitment/revised-offers', resourceType: 'recruitment-revised-offers', title: 'Display revised offer-Hiring Approved' },
  { path: 'recruitment/candidate-meetings', resourceType: 'recruitment-candidate-meetings', title: 'Meeting with Candidates List' },
  { path: 'recruitment/joining', resourceType: 'recruitment-joining', title: 'Convert to an Employee' },
  { path: 'recruitment/forms', resourceType: 'recruitment-forms', title: 'More Forms' },
  { path: 'settings/roles', resourceType: 'settings-roles', title: 'Role Define' },
  { path: 'settings/role-assign', resourceType: 'settings-role-assign', title: 'Role Assign' },
  { path: 'settings/role-view', resourceType: 'settings-role-view', title: 'View Role' },
  { path: 'organization/branches', resourceType: 'organization-branches', title: 'Branch/Location' },
  { path: 'organization/categories', resourceType: 'organization-categories', title: 'Employee Category' },
  { path: 'organization/departments', resourceType: 'organization-departments', title: 'Department' },
  { path: 'organization/designations', resourceType: 'organization-designations', title: 'Designations' },
  { path: 'organization/grades', resourceType: 'organization-grades', title: 'Grade (Pay Cadre)' },
  { path: 'settings/employee-id', resourceType: 'settings-employee-id', title: 'Configure Employee ID' },
  { path: 'payroll/calendar', resourceType: 'payroll-calendar', title: 'Salary Calendar' },
  { path: 'payroll/masters', resourceType: 'payroll-masters', title: 'Payroll Masters' },
  { path: 'organization/masters', resourceType: 'organization-masters', title: 'HR Masters' },
  { path: 'leave/policies', resourceType: 'leave-policies', title: 'Leave Code' },
  { path: 'leave/holidays', resourceType: 'leave-holidays', title: 'General Holidays' },
  { path: 'leave/flexible', resourceType: 'leave-flexible', title: 'Flexible Holidays' },
  { path: 'leave/weekly-off', resourceType: 'leave-weekly-off', title: 'Weekly Off' },
  { path: 'leave/special', resourceType: 'leave-special', title: 'Special Holiday' },
  { path: 'attendance/policy', resourceType: 'attendance-policy', title: 'Attendance Policy' },
  { path: 'payroll/heads', resourceType: 'payroll-heads', title: 'Salary Head' },
  { path: 'compliance/pt', resourceType: 'compliance-pt', title: 'Professional Tax' },
  { path: 'compliance/pf', resourceType: 'compliance-pf', title: 'Provident Fund' },
  { path: 'compliance/esic', resourceType: 'compliance-esic', title: 'ESIC' },
  { path: 'compliance/lwf', resourceType: 'compliance-lwf', title: 'Labour Welfare Fund' },
  { path: 'tax-calculator/sec-category', resourceType: 'tax-calculator-sec-category', title: 'TDS Sec. Category' },
  { path: 'tax-calculator/income-slab-cat', resourceType: 'tax-calculator-income-slab-cat', title: 'TDS Income Slab Category' },
  { path: 'tax-calculator/slabs', resourceType: 'tax-calculator-slabs', title: 'TDS Income Slabs' },
  { path: 'compliance/forms', resourceType: 'compliance-forms', title: 'More Compliance Forms' },
  { path: 'organization/forms', resourceType: 'organization-forms', title: 'More Forms' },
  { path: 'reports/employee-info', resourceType: 'reports-employee-info', title: 'Employee Information' },
  { path: 'reports/attendance', resourceType: 'reports-attendance', title: 'Monthly Attendance' },
  { path: 'reports/salary', resourceType: 'reports-salary', title: 'Monthly Salary' },
  { path: 'reports/salary-summary', resourceType: 'reports-salary-summary', title: 'Monthly Salary Summary' },
  { path: 'reports/salary-structure', resourceType: 'reports-salary-structure', title: 'Employee Salary Structure' },
  { path: 'documents/payroll', resourceType: 'documents-payroll', title: 'Payroll Forms' },
  { path: 'leave/cancel', resourceType: 'leave-cancel', title: 'Cancel Leave' },
  { path: 'leave/compoff-history', resourceType: 'leave-compoff-history', title: 'COL/COFF History' },
  { path: 'helpdesk/my-tickets', resourceType: 'helpdesk-my-tickets', title: 'Ticket History' },
  { path: 'helpdesk/feedback', resourceType: 'helpdesk-feedback', title: 'Suggestions/Feedback/Complains' },
  { path: 'exit/clearance', resourceType: 'exit-clearance', title: 'Department Clearance' },
  { path: 'exit/interview', resourceType: 'exit-interview', title: 'Exit Interview' },
  { path: 'approvals/leave', resourceType: 'approvals-leave', title: 'Leave' },
  { path: 'approvals/cancel-leave', resourceType: 'approvals-cancel-leave', title: 'Cancel Leave Application' },
  { path: 'approvals/compoff', resourceType: 'approvals-compoff', title: 'COL/COFF Application' },
  { path: 'approvals/travel', resourceType: 'approvals-travel', title: 'Travel Claim' },
  { path: 'approvals/advance', resourceType: 'approvals-advance', title: 'Advance Claim' },
  { path: 'approvals/loan', resourceType: 'approvals-loan', title: 'Loan/Advance' },
  { path: 'approvals/shift', resourceType: 'approvals-shift', title: 'Shift Change' },
  { path: 'approvals/optional-holiday', resourceType: 'approvals-optional-holiday', title: 'Optional Holidays' },
  { path: 'approvals/overtime', resourceType: 'approvals-overtime', title: 'Overtime (O.T)' },
];
