ALTER TABLE `Branch` ADD COLUMN `code` VARCHAR(191) NULL;
ALTER TABLE `Branch` ADD COLUMN `city` VARCHAR(191) NULL;
ALTER TABLE `Branch` ADD COLUMN `state` VARCHAR(191) NULL;
ALTER TABLE `Branch` ADD COLUMN `country` VARCHAR(191) NULL DEFAULT 'India';
ALTER TABLE `Branch` ADD COLUMN `phone` VARCHAR(191) NULL;
ALTER TABLE `Branch` ADD COLUMN `pincode` VARCHAR(191) NULL;
ALTER TABLE `Branch` ADD COLUMN `isActive` BOOLEAN NOT NULL DEFAULT true;
